# Generated by Django 4.1.5 on 2023-02-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pan',
            new_name='pan_card',
        ),
    ]
