# Generated by Django 4.1.5 on 2023-02-04 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_user_alter_userprofile_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
