# Generated by Django 4.1.5 on 2023-02-07 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_business_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='Description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
