# Generated by Django 4.1.5 on 2023-02-07 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_business_date_alter_business_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_type', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('expected_revenue', models.FloatField()),
                ('skill_set', models.TextField()),
                ('dateofinvestor', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
