# Generated by Django 4.1.5 on 2023-02-07 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_investorsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorsmodel',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.business'),
        ),
    ]
