# Generated by Django 4.1.5 on 2023-02-08 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_investorsmodel_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investorsmodel',
            old_name='dateofinvestor',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='investorsmodel',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investorsmodel',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='investorsmodel',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.business'),
        ),
        migrations.AlterField(
            model_name='investorsmodel',
            name='expected_revenue',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='investorsmodel',
            name='investment_type',
            field=models.CharField(choices=[('equity', 'Equity'), ('debt', 'Debt'), ('hybrid', 'Hybrid')], max_length=10),
        ),
    ]
