# Generated by Django 4.1.5 on 2023-02-10 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_business_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='Experience',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='Skills',
            field=models.CharField(blank=True, max_length=655, null=True),
        ),
        migrations.AlterField(
            model_name='investorsmodel',
            name='investment_type',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Banker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=100)),
                ('interest_rate', models.FloatField()),
                ('loan_amount', models.FloatField()),
                ('asset_type', models.CharField(max_length=100)),
                ('banker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
