# Generated by Django 4.1.5 on 2023-02-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_business_experience_alter_business_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banker',
            name='Description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
