# Generated by Django 4.1.5 on 2023-02-13 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_banker_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Business_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Advisors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user_query')),
            ],
        ),
    ]
