# Generated by Django 4.1.5 on 2023-02-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_query_advisors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banker',
            name='banker',
        ),
        migrations.RemoveField(
            model_name='business',
            name='User',
        ),
        migrations.RemoveField(
            model_name='investorsmodel',
            name='User',
        ),
        migrations.RemoveField(
            model_name='investorsmodel',
            name='business',
        ),
        migrations.RemoveField(
            model_name='user_query',
            name='Business_name',
        ),
        migrations.RemoveField(
            model_name='user_query',
            name='User',
        ),
        migrations.DeleteModel(
            name='Advisors',
        ),
        migrations.DeleteModel(
            name='Banker',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='InvestorsModel',
        ),
        migrations.DeleteModel(
            name='User_Query',
        ),
    ]
