# Generated by Django 4.1.5 on 2023-02-13 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0018_remove_banker_banker_remove_business_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Category', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_number', models.CharField(max_length=255)),
                ('Description', models.CharField(blank=True, max_length=600, null=True)),
                ('Experience', models.CharField(blank=True, max_length=555, null=True)),
                ('Skills', models.CharField(blank=True, max_length=655, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Active', models.BooleanField(default=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
