# Generated by Django 4.1.5 on 2023-02-13 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
        ('accounts', '0018_remove_banker_banker_remove_business_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user_query')),
            ],
        ),
    ]
